name: Build
on:
  push:
    branches-ignore:
      - "gh-pages"

jobs:
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0.0-beta"
      - name: Prepare
        run: |
          bundle update --bundler
          bundle install
      - name: Run tests
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: bundle exec fastlane test
